### PR TITLE
Add support for PHP 8.2

### PR DESCRIPTION
**Pull request by internalsystemerror**
This PR:
- Adds support for PHP 8.2
- Regenerates the lock file using PHP 7.4
- Adds `ext-simplexml` as a requirement to composer to fix psalm errors around `SimpleXMLElement`

### CODE REVIEW

**Comment by boesing** [comment]
Do we need to drop PHP 7.4 here? I still have a personal need for 7.4 and thus, if not mandatory, I prefer to keep it if possible.

**Comment by internalsystemerror** [comment]
Updated, this removes the need to do a `cs-fix` which mainly adds uses of unions and constructor properties.

**Comment by boesing** [comment]
Awesome. Thanks!

**Comment by internalsystemerror** [comment]
Apparently `webmozart/assert` say they support PHP 8.2 when they didn't and support was actually added in `1.11.0`, so I've bumped the minimum here.

**Comment by boesing** [comment]
Thanks, @internalsystemerror

**Pull request merged**
